# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formadepago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numeroProveedor', models.IntegerField(unique=True)),
                ('Contacto', models.CharField(blank=True, max_length=50)),
                ('Telefono', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('Email', models.EmailField(max_length=255)),
                ('formaDePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadepago.FormaDePago')),
            ],
        ),
    ]
