# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20170328_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
