# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papeles', '0002_auto_20170328_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papel',
            name='gramaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramajes.Gramaje'),
        ),
    ]
