# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0001_initial'),
        ('laminado', '0001_initial'),
        ('iva', '0001_initial'),
        ('acabado', '0001_initial'),
        ('gramajes', '0001_initial'),
        ('papeles', '0001_initial'),
        ('codpostales', '0001_initial'),
        ('clientes', '0001_initial'),
        ('comercial', '0001_initial'),
        ('modo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('isbn', models.DecimalField(blank=True, decimal_places=0, max_digits=13)),
                ('ancho', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cantidad', models.IntegerField(default=0)),
                ('paginas', models.IntegerField(default=0)),
                ('carasInterior', models.BooleanField(default=True)),
                ('carasPortada', models.BooleanField(default=False)),
                ('laminado', models.BooleanField(default=False)),
                ('solapas', models.BooleanField(default=False)),
                ('mmSolapas', models.DecimalField(blank=True, decimal_places=0, max_digits=3)),
                ('retractilado', models.BooleanField(default=False)),
                ('comentarios', models.CharField(max_length=255)),
                ('venta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fechaEntrada', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('fechaEntrega', models.DateField(null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('acabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acabado.Acabado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('codpostal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codpostales.CodigosPostales')),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Comercial')),
                ('gramajeInteriorDos', models.ManyToManyField(related_name='_parte_gramajeInteriorDos_+', to='gramajes.Gramaje')),
                ('gramajeInteriorUno', models.ManyToManyField(related_name='_parte_gramajeInteriorUno_+', to='gramajes.Gramaje')),
                ('gramajePortada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gramajes.Gramaje')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iva.Iva')),
                ('modo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modo.Modo')),
                ('papelInteriorDos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='papeles.Papel')),
                ('papelInteriorUno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='papeles.Papel')),
                ('papelPortada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='papeles.Papel')),
                ('tipoLaminado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='laminado.TipoLaminado')),
                ('transp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Transporte')),
            ],
            options={
                'ordering': ('parte',),
            },
        ),
    ]
