# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170328_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
